title: cellSTORM II
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This is the project page for the preprint "cellSTORM 2 - Nanoscopy on the chea(i)p"
  <br><br>
  The listed repository links will guide you through the different steps to replicate the result.
  <br><br>
  <a href="https://www.nanoimaging.de/">Find more in our Nanoimaging Webpage</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
